from os import getenv
from dotenv import load_dotenv

load_dotenv()

STRING = getenv("STRING")
STRING2 = getenv("STRING2")
STRING3 = getenv("STRING3")
STRING4 = getenv("STRING4")
STRING5 = getenv("STRING5")
STRING6 = getenv("STRING6")
STRING7 = getenv("STRING7")
STRING8 = getenv("STRING8")
STRING9 = getenv("STRING9")
STRING10 = getenv("STRING10")
STRING11 = getenv("STRING11")
STRING12 = getenv("STRING12")
STRING13 = getenv("STRING13")
STRING14 = getenv("STRING14")
STRING15 = getenv("STRING15")
STRING16 = getenv("STRING16")
STRING17 = getenv("STRING17")
STRING18 = getenv("STRING18")
STRING19 = getenv("STRING19")
STRING20 = getenv("STRING20")
STRING21 = getenv("STRING21")
STRING22 = getenv("STRING22")
STRING23 = getenv("STRING23")
STRING24 = getenv("STRING24")
STRING25 = getenv("STRING25")

API_ID = getenv("API_ID")
API_ID2 = getenv("API_ID2")
API_ID3 = getenv("API_ID3")
API_ID4 = getenv("API_ID4")
API_ID5 = getenv("API_ID5")
API_ID6 = getenv("API_ID6")
API_ID7 = getenv("API_ID7")
API_ID8 = getenv("API_ID8")
API_ID9 = getenv("API_ID9")
API_ID10 = getenv("API_ID10")
API_ID11 = getenv("API_ID11")
API_ID12 = getenv("API_ID12")
API_ID13 = getenv("API_ID13")
API_ID14 = getenv("API_ID14")
API_ID15 = getenv("API_ID15")
API_ID16 = getenv("API_ID16")
API_ID17 = getenv("API_ID17")
API_ID18 = getenv("API_ID18")
API_ID19 = getenv("API_ID19")
API_ID20 = getenv("API_ID20")
API_ID21 = getenv("API_ID21")
API_ID22 = getenv("API_ID22")
API_ID23 = getenv("API_ID23")
API_ID24 = getenv("API_ID24")
API_ID25 = getenv("API_ID25")

API_HASH = getenv("API_HASH")
API_HASH2 = getenv("API_HASH2")
API_HASH3 = getenv("API_HASH3")
API_HASH4 = getenv("API_HASH4")
API_HASH5 = getenv("API_HASH5")
API_HASH6 = getenv("API_HASH6")
API_HASH7 = getenv("API_HASH7")
API_HASH8 = getenv("API_HASH8")
API_HASH9 = getenv("API_HASH9")
API_HASH10 = getenv("API_HASH10")
API_HASH11 = getenv("API_HASH11")
API_HASH12 = getenv("API_HASH12")
API_HASH13 = getenv("API_HASH13")
API_HASH14 = getenv("API_HASH14")
API_HASH15 = getenv("API_HASH15")
API_HASH16 = getenv("API_HASH16")
API_HASH17 = getenv("API_HASH17")
API_HASH18 = getenv("API_HASH18")
API_HASH19 = getenv("API_HASH19")
API_HASH20 = getenv("API_HASH20")
API_HASH21 = getenv("API_HASH21")
API_HASH22 = getenv("API_HASH22")
API_HASH23 = getenv("API_HASH23")
API_HASH24 = getenv("API_HASH24")
API_HASH25 = getenv("API_HASH25")

BIO_MESSAGE = getenv("BIO")
SUDO = list(map(int, getenv("SUDO").split()))
GROUP_USERNAME = getenv("GROUP_USERNAME")
